# Generated by Django 6.0.2 on 2026-04-06 20:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa')], default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('mpesa_receipt_number', models.CharField(blank=True, default='', max_length=80)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, default='', max_length=32)),
                ('result_description', models.TextField(blank=True, default='')),
                ('raw_request_payload', models.JSONField(blank=True, null=True)),
                ('raw_callback_payload', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['-session__created_at'],
            },
        ),
    ]
