# Generated by Django 6.0.2 on 2026-06-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0002_gamesession_paused_at_and_more'),
        ('payments', '0003_payment_paid_status_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extension_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='extension_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('session_start', 'Session start'), ('paid_extend', 'Paid extend')], db_index=True, default='session_start', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='game_sessions.gamesession'),
        ),
    ]
