# Generated by Django 6.0.2 on 2026-04-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_sessions', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_secret', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('fault', 'Fault')], default='offline', max_length=20)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relay_state', models.BooleanField(default=False)),
                ('fault_state', models.CharField(default='none', max_length=100)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='stations.station')),
            ],
            options={
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('activate_station', 'Activate'), ('deactivate_station', 'Deactivate'), ('warning_mode', 'Warning'), ('reset_fault', 'Reset Fault'), ('ping', 'Ping')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_commands', to='game_sessions.gamesession')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.stationdevice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stationdevice',
            index=models.Index(fields=['device_id'], name='devices_sta_devid_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdevice',
            index=models.Index(fields=['status'], name='devices_sta_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdevice',
            index=models.Index(fields=['last_heartbeat_at'], name='devices_sta_lasthb_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device'], name='devices_dev_device_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['status'], name='devices_dev_status_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['created_at'], name='devices_dev_created_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status'], name='devices_dev_dev_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status', 'created_at'], name='devices_dev_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['session'], name='devices_dev_session_idx'),
        ),
    ]
