# Generated by Django 6.0.2 on 2026-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command',
            field=models.CharField(choices=[('activate_station', 'Activate'), ('deactivate_station', 'Deactivate'), ('warning_mode', 'Warning'), ('reset_fault', 'Reset Fault'), ('ping', 'Ping')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stationdevice',
            name='fault_state',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='stationdevice',
            name='relay_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device'], name='devices_dev_device_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['status'], name='devices_dev_status_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['created_at'], name='devices_dev_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdevice',
            index=models.Index(fields=['status'], name='devices_sta_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdevice',
            index=models.Index(fields=['last_heartbeat_at'], name='devices_sta_lasthb_idx'),
        ),
    ]
