# Generated by Django 6.0.2 on 2026-03-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_refactor_esp32_compat'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status'], name='devices_dev_dev_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='stationdevice',
            index=models.Index(fields=['device_id'], name='devices_sta_devid_idx'),
        ),
    ]
