# Generated by Django 6.0.2 on 2026-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_production_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'status', 'created_at'], name='devices_dev_queue_idx'),
        ),
    ]
