# Generated by Django 6.0.2 on 2026-04-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_stationdevice_updated_at_and_queue_index'),
        ('game_sessions', '0002_prepaid_compat_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_commands', to='game_sessions.gamesession'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['session'], name='devices_dev_session_idx'),
        ),
    ]
