# Generated by Django 6.0.2 on 2026-04-06 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='package_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='plan_kind',
            field=models.CharField(choices=[('legacy_hourly', 'Legacy hourly'), ('prepaid_package', 'Prepaid package')], db_index=True, default='legacy_hourly', max_length=32),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='pricing_type',
            field=models.CharField(blank=True, default='', help_text='E.g. time_block, match — informational for reporting.', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy hourly rate; null for pure prepaid package rows.', max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='pricingplan',
            index=models.Index(fields=['plan_kind', 'is_active'], name='pricing_pri_plan_ki_ced23c_idx'),
        ),
    ]
