# Generated by Django 6.0.2 on 2026-04-06 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('game_name', models.CharField(blank=True, default='', max_length=150)),
                ('plan_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('pricing_type_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('duration_minutes_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('expected_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_failed', 'Payment failed'), ('activation_pending', 'Activation pending'), ('activation_failed', 'Activation failed'), ('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=80)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('activation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device_activated_at', models.DateTimeField(blank=True, null=True)),
                ('device_deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='pricing.pricingplan')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('payment_initiated', 'Payment initiated'), ('payment_success', 'Payment success'), ('payment_failed', 'Payment failed'), ('activation_requested', 'Activation requested'), ('activated', 'Activated'), ('deactivation_requested', 'Deactivation requested'), ('deactivated', 'Deactivated'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('note', 'Note')], db_index=True, max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['station', 'status'], name='game_sessio_station_20244a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status', 'expected_end_time'], name='game_sessio_status_a5730d_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session', 'created_at'], name='game_sessio_session_d9b7f8_idx'),
        ),
    ]
