# Generated by Django 6.0.2 on 2026-03-27 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('start_time', models.DateTimeField()),
                ('expected_end_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='SessionExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_end_time', models.DateTimeField()),
                ('new_end_time', models.DateTimeField()),
                ('extended_at', models.DateTimeField(auto_now_add=True)),
                ('additional_minutes', models.PositiveIntegerField()),
                ('extended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_extensions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['-extended_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField()),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['paused_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['station', 'status'], name='game_sessio_station_20244a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status', 'expected_end_time'], name='game_sessio_status_a5730d_idx'),
        ),
    ]
