# Generated by Django 6.0.2 on 2026-04-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
        ('pricing', '0002_prepaid_compat_phase1'),
        ('stations', '0002_prepaid_compat_phase1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('payment_initiated', 'Payment initiated'), ('payment_success', 'Payment success'), ('payment_failed', 'Payment failed'), ('activation_requested', 'Activation requested'), ('activated', 'Activated'), ('deactivation_requested', 'Deactivation requested'), ('deactivated', 'Deactivated'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('note', 'Note')], db_index=True, max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='activation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='billing_kind',
            field=models.CharField(choices=[('legacy_hourly', 'Legacy hourly'), ('prepaid_stk', 'Prepaid (STK)')], db_index=True, default='legacy_hourly', max_length=32),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='device_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='device_deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='duration_minutes_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='merchant_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='plan_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, help_text='Selected package for prepaid; optional for legacy (uses station default).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='pricing.pricingplan'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pricing_type_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('completed', 'Completed'), ('pending_payment', 'Pending payment'), ('payment_failed', 'Payment failed'), ('paid', 'Paid'), ('activation_pending', 'Activation pending'), ('activation_failed', 'Activation failed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=32),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['billing_kind', 'status'], name='game_sessio_billing_1e9a07_idx'),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game_sessions.gamesession'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session', 'created_at'], name='game_sessio_session_d9b7f8_idx'),
        ),
    ]
