# Generated by Django 6.0.2 on 2026-06-06 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='remaining_seconds_at_pause',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('payment_failed', 'Payment failed'), ('activation_pending', 'Activation pending'), ('activation_failed', 'Activation failed'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=32),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('payment_initiated', 'Payment initiated'), ('payment_success', 'Payment success'), ('payment_failed', 'Payment failed'), ('activation_requested', 'Activation requested'), ('activated', 'Activated'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('extended', 'Extended'), ('deactivation_requested', 'Deactivation requested'), ('deactivated', 'Deactivated'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('note', 'Note')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SessionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('manual_extend', 'Manual extend')], db_index=True, default='manual_extend', max_length=40)),
                ('minutes_added', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_adjustments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='game_sessio_session_f1a493_idx'), models.Index(fields=['adjustment_type'], name='game_sessio_adjustm_cfa2ba_idx')],
            },
        ),
    ]
