# Generated by Django 6.0.2 on 2026-04-06 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('in_use', 'In use'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], db_index=True, default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='pricing.pricingplan')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='stations_st_status_1b55d9_idx')],
            },
        ),
    ]
