# Generated by Django 6.0.2 on 2026-04-06 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_prepaid_compat_phase1'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('in_use', 'In use'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['status', 'is_active'], name='stations_st_status_1b55d9_idx'),
        ),
    ]
